version: '3.7'
services:
  prod:
    container_name: ixo-faucet
    image: ghcr.io/ixofoundation/ixo-faucet:latest
    restart: unless-stopped
    ports:
      - 5000:80
  dev:
    container_name: ixo-faucet-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: ixo-faucet:dev
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 5000:80
